- python/_template/integration-test.py
- python/dazl/cli/ls.py
- python/dazl/client/_network_client_impl.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/_reader_sync.py
- python/dazl/model/ledger.py
- python/dazl/model/reading.py
- python/dazl/plugins/capture/fmt_pretty.py
- python/dazl/plugins/capture/model_capture.py
- python/dazl/plugins/capture/plugin_capture.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/model/__init__.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/tests/tutorials/post_office/Main.daml
- python/tests/unit/test_plugins_capture.py
Deeper support for using the Active Contract Set service to populate initial state.
This uses the ACS to get a sense of the initial state of contracts, and then subsequently uses the Transaction Event Stream to fill in missing data (effective time) and to filter out contracts where parties are not stakeholders (https://github.com/digital-asset/daml/issues/164).
> python: Deeper support for using the Active Contract Set service

- python/dazl/client/_network_client_impl.py
- python/dazl/client/api.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/util/dar.py
- python/dazl/util/io.py
Wait until DAR uploads are done _and_ packages are reported locally before returning.
> python: Make package upload blocking more "synchronous"

- python/_template/integration-test.py
- python/dazl/client/_network_client_impl.py
- python/dazl/client/_party_client_impl.py
- python/dazl/util/asyncio_util.py
- python/dazl/util/events.py
Moved some generic asyncio utils out of `_party_client_impl` and gave them more accurate names.
This is basically cleanup in preparation for more sweeping changes to `_party_client_impl` to support more fine-grained control over bots.
> python: Moved some generic asyncio utils into…`asyncio_utils.py`

- python/dazl/protocols/v1/pb_parse_event.py
Compatibility with SDK 0.13.16 in support of the removal of the deprecated `Identifier.name` field.
> python: Compatibility with SDK 0.13.16

- .gitignore
- Makefile
- python/Makefile
- python/dazl/__init__.py
* Make some of the `poetry` interactions more explicit in the Makefile itself, relying on marker files to indicate whether or not `poetry` commands need to be re-run.
* Add a target for generating a documentation tarball.
* Add a target for publishing releases.
> meta: Improvements to packaging and the release process.

- python/dazl/_gen/com/digitalasset/daml_lf_dev/daml_lf_1_pb2.py
- python/dazl/_gen/com/digitalasset/ledger/api/v1/admin/config_management_service_pb2.py
- python/dazl/_gen/com/digitalasset/ledger/api/v1/admin/config_management_service_pb2_grpc.py
- python/dazl/_gen/com/digitalasset/ledger/api/v1/admin/package_management_service_pb2.py
- python/dazl/_gen/com/digitalasset/ledger/api/v1/admin/party_management_service_pb2.py
- python/dazl/_gen/com/digitalasset/ledger/api/v1/admin/party_management_service_pb2_grpc.py
- python/dazl/_gen/com/digitalasset/ledger/api/v1/commands_pb2.py
- python/dazl/_gen/google/rpc/status_pb2.py
- python/dazl/damlast/daml_lf_1.py
- python/dazl/damlast/pb_parse.py
- python/dazl/damlast/types.py
- python/dazl/model/types.py
- python/dazl/pretty/_render_base.py
- python/dazl/pretty/render_daml.py
- tools/fetch_protos.py
Adds minimal support for DAML-LF 1.8.
Type synonyms are not yet well-supported, but this at least provides support for knowing they exist (and therefore allowing modules to be parsed).
> python: Support for DAML-LF 1.8.

- python/dazl/client/bots.py
- python/dazl/util/asyncio_util.py
Minor bug fix to support running tests under Python 3.7 and Python 3.8.
`pytest` uses the context parameter introduced to [`Future.add_done_callback`](https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.add_done_callback), but usage does not appear to be common in other contexts which is how this problem was not detected for so long. This allows certain `dazl` `asyncio` wrapper types to be used seamlessly with other `Future`s in this context.
> python: Minor bug fix to support running tests under Python 3.7/3.8

- python/dazl/__init__.py
- python/dazl/client/__init__.py
- python/dazl/client/_network_client_impl.py
- python/dazl/client/api.py
- python/dazl/model/core.py
- python/dazl/scheduler/_invoker.py
- python/dazl/util/tools.py
- python/tests/__init__.py
- python/tests/conftest.py
- python/tests/unit/test_all_types.py
- python/tests/unit/test_cli_ls.py
- python/tests/unit/test_complicated_types.py
- python/tests/unit/test_dar_file.py
- python/tests/unit/test_dotted_fields.py
- python/tests/unit/test_dynamic_dar_loading.py
- python/tests/unit/test_dynamic_parties.py
- python/tests/unit/test_event_handler_exceptions.py
- python/tests/unit/test_flask.py
- python/tests/unit/test_ledger_api_types.py
- python/tests/unit/test_map_support.py
- python/tests/unit/test_pending.py
- python/tests/unit/test_select.py
- python/tests/unit/test_select_nonempty.py
- python/tests/unit/test_server.py
- python/tests/unit/test_static_dump.py
- python/tests/unit/test_static_time.py
- python/tests/unit/test_threadsafe_methods.py
- python/tests/unit/test_write_cancel.py
Move most of the tests to run under a single sandbox, but using different Parties.
The remaining tests that have not yet been moved over test more specialized features of dazl, so moving them over to a single sandbox instance is more complicated. Those will be addressed in a subsequent PR.
The TL;DR of the changes:
* Introduce `Network.aio_new_party` and `Network.simple_new_party`, which imply an allocation of a new `Party`. Note that the current implementation does not yet actually call `PartyManagementService`, though it may in the future. It _does_, however, guarantee that new `Party` literals are created (via `uuid`), which is useful to keep the tests isolated from each other.
* Hardcoded `Party` literals in tests have been removed.
* Allow `ensure_dar` to be created _before_ the …
> python: Move most of the tests to run under a single sandbox

- .circleci/config.yml
- _fixtures/src/all-kinds-of/daml.yaml
- _fixtures/src/all-party/daml.yaml
- _fixtures/src/complicated/daml.yaml
- _fixtures/src/dotted-fields/daml.yaml
- _fixtures/src/map-support/daml.yaml
- _fixtures/src/pending/daml.yaml
- _fixtures/src/post-office/daml.yaml
- _fixtures/src/simple/daml.yaml
- _fixtures/src/test-server/daml.yaml
- _fixtures/src/upload-test/daml.yaml
- python/dazl/damlast/daml_lf_1.py
- python/dazl/damlast/types.py
- python/dazl/pretty/render_daml.py
- python/dazl/pretty/render_python.py
- python/tests/conftest.py
- python/tests/unit/test_dar_file.py
python: Upgrade tests to run under DAML SDK 1.3.0, and include some minor bug fixes for some of the more esoteric parts of the codebase that had incompatibilities with 1.3.0 that had gone undetected to this point.
> python: Upgrade tests to run under DAML SDK 1.3.0

- python/dazl/client/_reader_sync.py
- python/dazl/model/reading.py
The logic for `sortable_offset_height` was more complicated in pre-DAML SDK 1.0.0 ledgers:
https://github.com/digital-asset/daml/blob/6f8c3ad832ee0fa0c234c30d7312f73e703760f4/ledger-api/grpc-definitions/com/digitalasset/ledger/api/v1/ledger_offset.proto#L17-L21
In post-DAML SDK 1.0.0 ledgers, the logic is much more straightforward:
https://github.com/digital-asset/daml/blob/f050da78c9c8727b889bdac286156f19e2f938c4/ledger-api/grpc-definitions/com/daml/ledger/api/v1/ledger_offset.proto#L17-L18
Drop the pre-DAML SDK 1.0.0 implementation as older ledgers are no longer supported.
> python: Drop support for offsets in pre-DAML 1.0 ledgers.

- _fixtures/src/post-office/integration-test.py
- python/dazl/client/api.py
- python/dazl/damlast/daml_lf_1.py
- python/dazl/model/lookup.py
- python/dazl/model/types.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/tests/profiling/test_memory.py
- python/tests/tutorials/post_office/tutorial.py
- python/tests/unit/test_all_party.py
- python/tests/unit/test_all_types.py
- python/tests/unit/test_complicated_types.py
- python/tests/unit/test_dotted_fields.py
- python/tests/unit/test_dynamic_parties.py
- python/tests/unit/test_event_order.py
- python/tests/unit/test_flask.py
- python/tests/unit/test_map_support.py
- python/tests/unit/test_pb_serialize.py
- python/tests/unit/test_pending.py
- python/tests/unit/test_select.py
- python/tests/unit/test_select_nonempty.py
- python/tests/unit/test_server.py
- python/tests/unit/test_simple_client_api.py
- python/tests/unit/test_static_dump.py
- python/tests/unit/test_template_reverse_globs.py
- python/tests/unit/test_threadsafe_methods.py
Drop support for template references of the form `PKG:MODULE.ENTITY` (with a dot between modules and entities) and exclusively support `PKG:MODULE:ENTITY`(with a colon between modules and entities).
Annoyingly, most of the tests still used the old format given their age, so the majority of files touched were the tests.
> python: Drop support for historical template formats.

- _fixtures/src/all-kinds-of/AllKindsOf.daml
- python/dazl/protocols/v1/pb_parse_event.py
- python/tests/unit/test_all_types.py
Fix a problem that caused `Enum` Protobuf values not to be unpacked properly.
> python: Fix handling of Enum values.

- python/Makefile
- python/dazl/server/metrics.py
- python/dazl/server/oauth_callback.py
- python/poetry.lock
- python/pyproject.toml
Removed `pyyaml` as a dependency (`dazl` no longer uses it in any way), and move many of the remaining dependencies to optional dependencies that can be selectively opted in if those features are used.
> python: Update the dependencies list.

- python/dazl/damlast/visitor.py
- python/dazl/model/types.py
- python/dazl/model/writing.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/v1/pb_parse_metadata.py
- python/dazl/util/prim_types.py
- python/dazl/util/tools.py
* Fix a few imports used only for types.
* Add `parse_archive`, which should generally start to be favored in the codebase as the way to load DAML-LF archives. There are a few conventions scattered throughout the codebase on different parsing techniques and they should be consolidated.
* Add `get_matches`, which better codifies the behavior of the special `'*'` literal in certain contexts, such as fetching wildcard package ID and/or template names.
> python: Miscellaneous small fixes/additions.

- python/dazl/damlast/__init__.py
- python/dazl/damlast/daml_lf_1.py
- python/dazl/damlast/pb_parse.py
python: Start to use __all__ in places where star imports and automatic documentation are to be used more heavily.
Sphinx can use the combination of `__all__` with the `:members:` declaration to "automatically" list all members; separately, using `__all__` provides a list of the specific importable symbols, thereby making star imports work better without also the additional clutter of imports that are local to a file.
There are a handful of places in the codebase that are currently `import`'ing symbols from the "wrong place"; these will be patched up as `__all__` is added to more parts of the codebase.
> python: Start to use __all__

- python/dazl/damlast/visitor.py
Somehow `TypeVisitor`, which is meant to be an exhaustive handler over all `dazl.damlast.daml_lf_1.Type` cases, was _not_ exhaustive. There are still pockets of `dazl` that prevent `mypy` from being turned on, but it definitely would have caught this. :-/
> python: Fix TypeVisitor so that it actually is exhaustive.

- python/dazl/damlast/__init__.py
- python/dazl/damlast/parse.py
- python/dazl/protocols/v1/pb_parse_metadata.py
python: Introduce dazl/damlast/parse.py and move parsing logic there.
The remaining contents of `dazl/protocols/v1/pb_parse_metadata.py` will soon be deprecated, as the code in this file was built under old assumptions that make lazy package loading (#126) harder to implement. Specifically, an upcoming rewrite of value encoding/decoding will drop the requirement that packages and their dependencies must always be present at the time of parsing.
> python: Introduce dazl/damlast/parse.py and move parsing logic there.

- python/dazl/damlast/__init__.py
- python/dazl/damlast/builtins.py
- python/dazl/damlast/daml_types.py
- python/dazl/damlast/types.py
- python/dazl/damlast/util.py
- python/dazl/pretty/render_python.py
- python/tests/unit/test_pretty_daml.py
Add convenience functions for constructing `dazl.damlast.daml_lf_1.Type` objects.
The only place these objects are currently constructed en masse is in `ProtobufParser` (https://github.com/digital-asset/dazl-client/blob/4baab66825ae061014d9045ec64e212c7df27572/python/dazl/damlast/pb_parse.py); however, ideally `ProtobufParser` remains hermetic and possibly code-generated, so I've opted to _not_ repoint constructions of `Type` objects to these functions. However, there are some tests where these types are constructed; this usage has been replaced with the convenience functions, which hopefully illustrate how these utility functions can aid readability at the call site.
These functions are intended to be used in shimming code that converts usages of `dazl.model.types.Type` to …
> python: Add convenience functions for constructing Type objects

- python/dazl/client/_writer_verify.py
- python/dazl/client/config.py
- python/dazl/client/state.py
- python/dazl/damlast/__init__.py
- python/dazl/damlast/compat.py
- python/dazl/damlast/lookup.py
- python/dazl/damlast/util.py
- python/dazl/model/core.py
- python/dazl/model/reading.py
- python/dazl/model/writing.py
- python/dazl/pretty/table/fmt_pretty.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_parse_metadata.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/dazl/util/dar.py
- python/tests/unit/test_capture_app.py
- python/tests/unit/test_command_builder.py
- python/tests/unit/test_pb_serialize.py
Adapt `ContractId` and `Command` classes to understand and use `TypeConName`; deprecated old-style `Type` s. As part of the ongoing work to address #126, these types need to speak `daml.damlast.daml_lf_1.Type` instead of `dazl.model.types.Type`.
The fields of `ContractId` and `Command` that returned `TypeReference`/`Type` are now marked as deprecated. This preserves code that might be using type information, while also allowing a new value serializer to make use of the new types.
> python: Adapt ContractId and Command classes to use new Types

- _fixtures/src/post-office/integration-test.py
- python/dazl/__init__.py
- python/dazl/_logging.py
- python/dazl/cli/__init__.py
- python/dazl/client/runner.py
- python/dazl/util/io.py
- python/dazl/util/logging.py
- python/pytest.ini
- python/tests/profiling/test_memory.py
- python/tests/unit/dars.py
- python/tests/unit/test_flask.py
python: Improvements to logging infrastructure.
* Move the logging code to `dazl/_logging.py`.
* Deprecate `dazl.setup_default_logger`; applications should instead prefer to configure their own loggers (simply calling `logging.basicConfig()` is a good-enough alternative for most applications).
* Use `pytest`'s native support for logging the output of loggers, rather than the slightly more indirect route of writing log output to stdout, and then having `pytest` look at stdout.
* Before #66, `dazl` used Python's built-in `unittest` framework, which has no integration with Python's built-in `logging` framework. `dazl.util.io.StdoutStreamWrapper` existed solely to support `logger`/`unittest` integration, so it has been dropped.
* Add `LOG.verbose_timed`, `LOG.debug_timed`, and …
> python: Improvements to logging infrastructure.

- python/tests/unit/test_dar_upload.py
- python/tests/unit/test_dotted_fields.py
- python/tests/unit/test_dynamic_dar_loading.py
- python/tests/unit/test_package_loading.py
In the next version of dazl, package loading will now "sometimes" be lazy. This changes the way that message serialization/parsing code works in a very fundamental way, which has also opened up opportunities to prune some code that is not often used.
* `PackageAddedEvent` is "almost" deprecated because it doesn't (and can't) work in a sane way with lazy package loading; code like the following will no longer work the same way (and the handler itself will eventually be removed):
```python
@client.package_added():
def handle(event):
print('A new package came in!')
```
In the next version of dazl, if you depend on a package, simply load it; package loading will be both lazier and more explicit, rather than trying to sync packages in the background and present a consistent coherent package …
> python: Invalidate tests that will soon no longer be valid.

- _fixtures/src/post-office/integration-test.py
- python/dazl/cli/ls.py
- python/dazl/damlast/__init__.py
- python/dazl/damlast/errors.py
- python/dazl/damlast/pkgfile.py
- python/dazl/pretty/table/write.py
- python/dazl/util/dar.py
- python/tests/unit/test_dar_file.py
- python/tests/unit/test_historical_dar_parsing.py
- python/tests/unit/test_package_loading.py
Deprecate `dazl.util.dar.DarFile` and its API for fetching data as a `PackageStore`.
The new `DarFile` is a bit lighter-weight and does not do any internal caching, and parsing happens _synchronously_. Asynchronous parsing (to avoid blocking the main thread) will be handled by a new dedicated package loader in an upcoming PR.
> python: Introduce dazl.damlast.pkgfile.DarFile

- python/dazl/client/_network_client_impl.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/api.py
- python/dazl/client/config.py
- python/dazl/client/pkg_loader.py
- python/dazl/damlast/__init__.py
- python/dazl/damlast/lookup.py
- python/dazl/damlast/pkgfile.py
- python/dazl/damlast/protocols.py
- python/dazl/model/ledger.py
- python/dazl/model/lookup.py
- python/dazl/model/reading.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/tests/conftest.py
- python/tests/unit/dars.py
- python/tests/unit/test_damlast_lookup.py
- python/tests/unit/test_pkg_loader.py
- python/tests/unit/test_pkg_loader_do_with_retry.py
Introduce `SymbolLookup` and `PackageLoader`, the intended replacements for `PackageStore`.
`PackageLookup` and `SymbolLookup` aren't wired into any of the infrastructure of `dazl` yet; that will be coming in a subsequent PR.
This change actually manages to be backwards/forwards compatible because `PackageLookup`, a lazier version of `PackageStore`, doesn't actually contain any packages until they are requested; this means if for whatever reason a version of `dazl` were cut on this commit, the `PackageStore` would continue to try to remain up-to-date in its currently "almost working" state, and the `PackageLookup` would simply remain empty.
> python: Introduce SymbolLookup and PackageLoader

- python/dazl/damlast/lookup.py
- python/dazl/damlast/util.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/dazl/values/__init__.py
- python/dazl/values/canonical.py
- python/dazl/values/context.py
- python/dazl/values/json.py
- python/dazl/values/mapper.py
- python/dazl/values/protobuf.py
- python/dazl/values/pysample_encoder.py
- python/tests/unit/test_values_canonical.py
- python/tests/unit/test_values_json_decoder.py
- python/tests/unit/test_values_protobuf.py
Introduce ValueMapper, a replacement for Serializer on the write side and a replacement for pb_parse_event (which was gRPC only) on the read side.
Unlike `Serializer`, `ValueMapper` uses DAML-LF `dazl.damlast.daml_lf_1.Type` objects instead of `dazl`'s original `dazl.model.types.Type` object, which means extending dazl to handle new types introduced in DAML-LF in the future will be much easier. Additionally the new mappers have no implicit dependency on `PackageStore` fully-resolved types behavior as the mappers are built on `SymbolLookup`, which has well-defined behavior for how it handles a missing package lookup.
This PR was split out of #143 simply because #143 was too large. This PR's focus is on introducing the new implementation into the codebase (along with its tests); #143 will …
> python: Introduce ValueMapper

- python/dazl/cli/ls.py
- python/dazl/client/_network_client_impl.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/_writer_verify.py
- python/dazl/client/api.py
- python/dazl/client/state.py
- python/dazl/damlast/daml_types.py
- python/dazl/damlast/expand.py
- python/dazl/model/reading.py
- python/dazl/model/writing.py
- python/dazl/pretty/_render_base.py
- python/dazl/pretty/render_daml.py
- python/dazl/protocols/v0/json_ser_command.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/dazl/util/dar.py
- python/dazl/values/context.py
- python/tests/unit/test_dar_upload.py
- python/tests/unit/test_event_order.py
- python/tests/unit/test_flask.py
- python/tests/unit/test_pb_serialize.py
- python/tests/unit/test_pretty_daml.py
Fix a race condition that could cause failures when trying to use packages around the same time they are uploaded to the ledger.
This is the one that switches the primary encode/decoder to the new `ValueMapper` introduced in #144, and uses the `SymbolLookup`/`PackageLoader` combination from #142.
A few long-standing TODOs in the guts of dazl have also now been dropped, particularly around ordering of when packages get loaded, and inopportune polling as it relates to trying to make sure the appropriate packages are available at the appropriate time (which turns out to be impossible to do).
> python: Fix a package load race condition

- python/poetry.lock
- python/pyproject.toml
gRPC 1.32.0 is the first version of the library to include _native_ support for `asyncio`, which we'll explore using to help slim down some of the scarier and weirder corners of `dazl`.
> python: Update the lock file; bump up minimum gRPC version to 1.32.0.

- python/dazl/cli/__init__.py
- python/dazl/cli/metadata.py
- python/dazl/client/_network_client_impl.py
- python/dazl/client/config.py
- python/dazl/client/errors.py
- python/dazl/client/state.py
- python/dazl/damlast/errors.py
- python/dazl/model/core.py
- python/dazl/prim/__init__.py
- python/dazl/prim/errors.py
- python/dazl/protocols/autodetect.py
- python/dazl/protocols/errors.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/server/management.py
- python/dazl/util/proc_util.py
Move `dazl.model.errors` classes closer to the places where they are actually used.
The central `dazl.model` package triggers circular imports too easily, particularly as I try to move/deprecate symbols in preparation for v8.
> python: Move error definitions out of a consolidated package to avoid circular imports

- python/dazl/client/_party_client_impl.py
- python/dazl/client/state.py
- python/dazl/model/core.py
- python/dazl/query/__init__.py
- python/dazl/query/query.py
- python/tests/unit/test_matches.py
Continuing to move more code out of `dazl.models`.
This code will actually remain (and possibly be expanded) in v8; query filtering is one area where the HTTP JSON API provides a richer API than the gRPC Ledger API, and in general some primitive client-side filtering has proved useful in the past.
> python: Move dazl.model.core.ContractMatch to dazl.query.

- python/dazl/client/_party_client_impl.py
- python/dazl/client/api.py
- python/dazl/client/state.py
- python/dazl/model/core.py
- python/dazl/model/reading.py
Continuing to move more code out of `dazl.models`.
These types are actually only used for the ACS, and support for querying the ACS as an in-memory database will not be part of the v8 API.
> python: Move the ACS types in dazl.model.core closer to their actual usage

- python/dazl/__init__.py
- python/dazl/client/_run_level.py
- python/dazl/values/context.py
- python/docs/index.rst
- python/tests/unit/test_server.py
Just a few last rewrites before remaking the `dazl.model` package as deprecated links back to the places where types have actually been moved to.
> python: Remove a few last usages of the model package.

- python/dazl/__init__.py
- python/dazl/client/_events.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/_writer_verify.py
- python/dazl/client/api.py
- python/dazl/client/bots.py
- python/dazl/client/commands.py
- python/dazl/model/writing.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/commands.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/tests/unit/test_command_builder.py
python: Prepare the `Command` classes for the new v8 API (#108).
* Rename `CreateCommand`/`CreateAndExerciseCommand`/`ExerciseCommand`/`ExerciseByKeyCommand` fields to match the properties as they exist in the JavaScript ledger bindings (https://docs.daml.com/app-dev/bindings-ts/daml-ledger/classes/_index_.ledger.html).
* Split these classes into `dazl.protocols.commands.*Command`, and deprecated counterparts in `dazl.clients.commands.*Command` that are meant to help with the v8 transition but will be removed in v9.
* Remove usage of `dataclass` in `Command`, as dataclasses don't have a particularly straightforward way of deprecating fields.
> python: Command hierarchy revamp

- python/dazl/__init__.py
- python/dazl/client/_writer_verify.py
- python/dazl/client/bots.py
- python/dazl/client/commands.py
- python/dazl/client/ledger.py
- python/dazl/client/pkg_loader.py
- python/dazl/ledger/__init__.py
- python/dazl/ledger/api_types.py
- python/dazl/ledger/pkgloader_aio.py
- python/dazl/ledger/pkgloader_aio_compat.py
- python/dazl/model/writing.py
- python/dazl/protocols/serializers.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/tests/unit/test_command_builder.py
- python/tests/unit/test_pkg_loader.py
- python/tests/unit/test_pkg_loader_do_with_retry.py
This originally was just going to be about adding read-side objects, but in looking more closely at some names (and also the Daml TypeScript library) it became clear that we could do better here.
So this PR:
* Moves the nascent v8 api into `dazl.ledger` and out of `dazl.protocols`.
* The v5 API was split between `dazl.protocols` and `dazl.client`, but the v8 API is thin enough that it doesn't need two layers.
* The v8 API won't actually share any common code with `dazl.protocols`; earlier iterations used more of `dazl.protocols`' existing code, but incorporating the gRPC asyncio changes turned out to be more invasive, requiring parallel implementations.
* Add new definitions for `CreateEvent` and `ArchiveEvent`. They will be _purely_ data classes; I'm not sure it will be possible to …
> python: Move the nascent v8 api into dazl.ledger

- python/dazl/damlast/lookup.py
- python/dazl/ledger/__init__.py
- python/dazl/ledger/api_types.py
- python/dazl/ledger/grpc/codec_aio.py
- python/dazl/ledger/pkgcache.py
- python/dazl/ledger/pkgloader_aio_compat.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/tests/unit/test_pb_serialize.py
This is intended to be a much more streamlined and straightforward implementation of Protobuf/gRPC encoding/decoding than `dazl.protocols.v1.pb_parse_event` and `dazl.protocols.v1.pb_ser_command`, both of which have gotten a bit too complicated over the years.
This isn't a _direct_ replacement because `dazl.ledger.Codec` understands `asyncio` natively, whereas the older classes operate in a blocking fashion because of how we used to use gRPC.
> python: Add the v8 codec.

- python/dazl/protocols/autodetect.py
- python/dazl/protocols/v1/grpc.py
Somewhere along the line, `dazl` lost support for getting and setting static time, which isn't really that big of a deal considering that the old time model hasn't really been used since Daml 1.0.
These functions are also not exposed through `Network` or `PartyClient` in any way, so it's highly unlikely anyone was using these. There isn't a way to _get_ the current time either, so even more so does this code likely have limited utility.
> python: Drop low-level set_time support.

- python/.gitignore
- python/dazl/client/commands.py
- python/dazl/ledger/__init__.py
- python/dazl/ledger/api_types.py
- python/docs/dazl.ledger.rst
- python/docs/dazl.protocols.rst
- python/docs/dazl.rst
Some minor documentation fixes here and there, mostly in `dazl.ledger.api_types`.
> python: Documentation fixes for dazl.ledger.api_types.

- python/dazl/ledger/__init__.py
- python/dazl/ledger/config/__init__.py
- python/dazl/ledger/config/access.py
- python/dazl/ledger/config/argv.py
- python/dazl/ledger/config/exc.py
- python/dazl/ledger/config/ssl.py
- python/dazl/ledger/config/url.py
- python/docs/dazl.ledger.config.rst
- python/docs/dazl.rst
- python/docs/migrating.rst
- python/tests/unit/test_ledger_config_argv.py
- python/tests/unit/test_ledger_config_url.py
Add classes for the new config system that will be used with the v8 API (#109).
Some goals of this implementation:
* Support multiparty submissions more effectively, particularly add support for specifying `--act-as` and `--read-as`
* Be less "magical" than the current implementation (see [dazl/util/config.py](https://github.com/digital-asset/dazl-client/blob/master/python/dazl/util/config.py) and [dazl/util/config_meta.py](https://github.com/digital-asset/dazl-client/blob/master/python/dazl/util/config_meta.py))
* `Network.set_config(**kwargs)` takes a lot of options, but because it's defined as "kwargs", the documentation doesn't show up in an IDE which also hurts discoverability.
* Be easier to plug into client applications; `dazl.run` has been deprecated for a while, but because it …
> python: Add the new v8 config objects, with docs.

- python/dazl/client/api.py
- python/dazl/client/state.py
- python/dazl/ledger/grpc/codec_aio.py
- python/dazl/query/__init__.py
- python/dazl/query/query.py
`from __future__ import annotations` (available in Python 3.7) enables type forward references to work, which means the quotes are finally no longer needed around type annotations in the dazl codebase.
> python: Mostly formatting tweaks pulled up from #108.

- python/mypy.ini
- python/poetry.lock
- python/pyproject.toml
Add a `grpc-stubs` library; the `grpcio` library doesn't support typing natively, but it turns out there are stub libraries out int he wild that can split the difference!
> python: Add a grpc-stubs library.

- python/dazl/__init__.py
- python/dazl/ledger/config/access.py
- python/dazl/ledger/config/ssl.py
- python/dazl/ledger/errors.py
- python/dazl/ledger/grpc/__init__.py
- python/dazl/ledger/grpc/channel.py
- python/dazl/ledger/grpc/codec_aio.py
- python/dazl/ledger/grpc/conn_aio.py
- python/dazl/ledger/stream_aio.py
- python/dazl/prim/__init__.py
- python/dazl/prim/basic.py
- python/dazl/protocols/core.py
- python/dazl/protocols/errors.py
- python/dazl/query/__init__.py
- python/docs/index.rst
- python/docs/migrating.rst
- python/tests/unit/test_protocol_ledgerapi.py
Introduces a new API that embraces multi-party subscriptions, and modernizes and simplifies the implementation.
```py
async def main(token):
async with dazl.connect(url, token=token) as conn:
await conn.create("Some:Thing", { ... })
async with conn.stream("Some:Thing") as stream:
async for event in stream:
print(event)
if i_feel_like_it:
break
elif event.cdata["name"] == "Batman":
await buy_batmobile(event)
```
`dazl` turns four years old in May 2021, and many of the design decisions that it was originally built with (even predating the Daml gRPC Ledger API as introduced in October 2018) no longer apply:
* `SubmitAndWait`: older versions of the ledger API _only_ had a `CommandSubmissionService.Submit` call, which required clients to listen to `TransactionStream` events in order to know …
> python: Next-gen dazl connection API

- python/dazl/damlast/types.py
- python/dazl/model/types.py
- python/dazl/protocols/v1/pb_parse_metadata.py
- python/dazl/util/asyncio_util.py
* Get rid of two warnings that would come about from normal usage.
* Make some of the older dazl `Type` classes more obviously deprecated (PyCharm doesn't seem to mark subclasses as deprecated when their parent classes are deprecated, which is a little annoying.)
> python: Reduce the amount of noise that comes from normal usage of dazl.

- python/dazl/client/api.py
- python/dazl/client/state.py
- python/dazl/damlast/lookup.py
- python/dazl/model/writing.py
- python/dazl/protocols/v1/grpc.py
- python/tests/unit/test_acs_find_active.py
- python/tests/unit/test_autoload_explicit_packages.py
Fix a problem where fully-specific template names for ACS fetches would fail when no contracts are discovered.
> python: Fix ACS fetches on empty sets

- .circleci/config.yml
- .circleci/install-daml
- .circleci/install-java
- .circleci/install-jq
- _build/jdk-install
Something recently changed in CircleCI's base image that caused our specific way of installing `poetry` to no longer work.
Additionally, `poetry` is actually installed in CircleCI's base image now (it wasn't at the time of #4) so there isn't actually even a reason to try to fix the installer at all.
Separately, improve and clean up the way that dependencies in _general_ are pulled down and installed, particularly the JVM.
> circleci: Use the poetry image in CircleCI's base image.

- .circleci/config.yml
Apparently trying to switch to CircleCI's base images for Blackduck (#202) has caused problems; so revert that, but preserve the way we're caching `jq` because that still seems to work.
This still requires some further investigation because there is nothing obviously wrong with the original build except for a weird error:
```
2021-04-19 13:55:40 UTC ERROR [main] --- Could not retrieve the bearer token
com.synopsys.integration.exception.IntegrationException: Could not perform the authorization request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at com.synopsys.integration.rest.support.AuthenticationSupport.attemptAuthentication(AuthenticationSupport.java:90) …
```
> meta: Fix Blackduck integration

- python/dazl/model/types.py
- python/dazl/model/types_store.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/autodetect.py
- python/dazl/protocols/oauth.py
- python/dazl/protocols/v0/json_ser_command.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/model/__init__.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_parse_metadata.py
- python/dazl/protocols/v1/pb_ser_command.py
This is in preparation for simply lifting the implementation of `dazl.protocols` as-is on the release branch into `master` (see #207).
On `master`, the `dazl.model` package is entirely deprecated; this will be the case for dazl v7.5 as well, but one thing required to make that a reality is that _no_ package can depend on `dazl.model`, as otherwise circular imports could be introduced. This PR moves the relevant imports either under a `if TYPE_CHECKING:` guard, or internally into functions that specifically still refer to those symbols.
This also drops the usage of `dazl.protocols.v1.model`, which was meant to be a convenient collection of Protobuf types. (I mostly dropped this because in trying to prepare this PR, I was looking for imports that contained the word `model` and those were in …
> python: Break dazl.protocols' compile-time dependency on dazl.models.

- python/dazl/prim/basic.py
- python/dazl/prim/complex.py
- python/dazl/prim/contracts.py
- python/dazl/prim/datetime.py
- python/dazl/prim/numbers.py
This is a backport of the files in `dazl/prim` exactly as-is from the release branch, _except_ for also including the regular expressions defined here, which have been added to `master` but not on the release branch.
https://github.com/digital-asset/daml/blob/988f3e509ebc3f164cc355fcb9b65e2eafa67db6/ledger-api/grpc-definitions/com/daml/ledger/api/v1/value.proto#L18-L21
> python: Backport dazl/prim/*.py from the v7 release branch.

- python/dazl/values/canonical.py
- python/dazl/values/context.py
- python/dazl/values/json.py
- python/dazl/values/mapper.py
- python/dazl/values/protobuf.py
- python/dazl/values/pysample_encoder.py
- python/dazl/values/string.py
More backports in service of #207.
The only notable difference between this and the release branch contents is the release branch still supports deprecated `ContractId`'s…this needs to be restored too, but can only be done in conjunction with resurrecting the deprecated type system.
> python: Backport dazl/values/*.py from the v7 release branch.

- python/dazl/client/_network_client_impl.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/events.py
- python/dazl/client/ledger.py
- python/dazl/model/lookup.py
- python/dazl/protocols/events.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/tests/unit/test_damlast_lookup_normalizations.py
Some more refactors ahead of reintroducing `dazl.model.types` and `dazl.model.types_store` from the v7 release branch back on master.
In particular this reintroduces the deprecated `BaseEvent.store` and `LedgerMetadata.store` properties, but populates them with `object()` instead of an instance of `dazl.model.types_store.PackageStore`, as well as bringing back some of the code that supports deprecated type identifiers.
> python: Some more refactors ahead of reintroducing dazl.model.types/types_store

- python/poetry.lock
- python/pyproject.toml
When further trying to reconcile `master` and `release-7.3`, I realized that I forgot to add the `dataclasses` backport library back on `master`, which is required for Python 3.6.
The tests unfortunately do _not_ catch this because `dataclasses` is still pulled in transitively as a dev-time dependency, but omitting this would have broken Python 3.6 compatibility.
> python: Add dataclasses as a dependency; run "poetry update".

- python/dazl/client/events.py
- python/dazl/client/ledger.py
- python/dazl/client/pkg_loader.py
- python/dazl/damlast/compat.py
- python/dazl/damlast/lookup.py
- python/dazl/damlast/types.py
- python/dazl/damlast/util.py
- python/dazl/ledger/pkgloader_aio.py
- python/dazl/ledger/pkgloader_aio_compat.py
- python/dazl/model/__init__.py
- python/dazl/model/ledger.py
- python/dazl/model/lookup.py
- python/dazl/model/types.py
- python/dazl/model/types_store.py
- python/dazl/protocols/events.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_parse_metadata.py
- python/mypy.ini
- python/tests/unit/test_template_reverse_globs.py
Restore some deprecated symbols that are scheduled for removal in dazl v8 (partial revert of #159).
This essentially allows the dazl v7.5 release to be cut off `master`, as `master` will contain the principal symbols that are scheduled to be removed as part of v8. In detail:
In general, files that have been removed on `master` have been restored with the contents of the `release-7.3` branch _instead_ of the state as they existed pre-#159, as the v7 release branch has evolved considerably over the last month.
Copied from the `release-7.3` branch with minimal modifications:
* `dazl.model.types` and `dazl.model.types_store`, with the exception of converting `dazl.model.types_store.PackageProvider` to a `Protocol` to avoid the need for a runtime dependency on …
> python: Restore some symbols deprecated for v8

- python/dazl/pretty/__init__.py
- python/dazl/pretty/_module_builder.py
- python/dazl/pretty/_render_base.py
- python/dazl/pretty/render_csharp.py
- python/dazl/pretty/render_csv.py
- python/dazl/pretty/render_daml.py
- python/dazl/pretty/render_python.py
- python/dazl/pretty/table/fmt_pretty.py
- python/dazl/pretty/table/model.py
Replace the contents of `dazl/pretty` on master with files from the v7 release branch.
This undoes some of the changes in #159, but also makes it so that `dazl/pretty` typechecks on master.
Depends on #211, which reintroduces the `dazl.model.types` symbols that `dazl/pretty` depends on in v7.
> python: Replace the contents of dazl/pretty on master with v7

- python/dazl/model/core.py
- python/dazl/values/context.py
Backport deserializing ContractId's into a backwards-compatible representation.
This restores the "old" `ContractId`'s on `master`; they were originally slated for removal in v8, and although is still planned, `master` is morphing into dazl v7.5 (per #207).
> python: Backport deserializing backwards-compatible ContractId's

- python/dazl/cli/metadata.py
- python/dazl/cli/tail.py
Backport a few type hints fixes from v7 back to `master`.
> python: Backport dazl.cli type fixes from v7.

- python/dazl/server/management.py
- python/dazl/server/metrics.py
A few type hints taken from the v7 branch and backported to `master`.
> python: Backport typing fixes for dazl.server from the v7 branch.

- python/Makefile
- python/dazl/__init__.py
- python/mypy.ini
Backports of #195/#196 from the release branch to `master`.
> python: Fixes to the build (backports of #195, #196).

- python/dazl/util/__init__.py
- python/dazl/util/asyncio_util.py
- python/dazl/util/config_meta.py
- python/dazl/util/dar.py
- python/dazl/util/dar_repo.py
- python/dazl/util/path_util.py
- python/dazl/util/prim_types.py
- python/dazl/util/tools.py
Type fixes and more resurrection of dead code in `dazl.util`.
This code will still be removed as part of dazl v8, but will remain in dazl v7.5.
> python: Backport dazl.util from v7.

- python/dazl/client/_party_client_impl.py
- python/dazl/client/pkg_loader.py
- python/dazl/ledger/pkgloader_aio.py
- python/dazl/ledger/pkgloader_aio_compat.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/autodetect.py
- python/dazl/protocols/events.py
- python/dazl/protocols/oauth.py
- python/dazl/protocols/v0/__init__.py
- python/dazl/protocols/v0/json_ser_command.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/model/__init__.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_ser_command.py
Backport of the typing fixes from the `dazl.protocols` package from the release branch onto `master`.
Also fixes some subtle bugs in the new dazl v8 API, as some of this code is shared between the old and new worlds.
> python: Backport dazl.protocols from v7.

- python/dazl/damlast/_builtins_meta.py
- python/dazl/damlast/builtins.py
- python/dazl/damlast/compat.py
- python/dazl/damlast/eval_scope.py
- python/dazl/damlast/expand.py
- python/dazl/damlast/lookup.py
- python/dazl/damlast/parse.py
- python/dazl/damlast/pkgfile.py
- python/dazl/damlast/protocols.py
- python/dazl/damlast/types.py
- python/dazl/damlast/util.py
- python/dazl/damlast/visitor.py
- python/dazl/model/lookup.py
- python/dazl/server/management.py
This is basically the last of the backports of type fixes from the v7 branch; `master` still doesn't 100% pass `mypy`'s muster yet, but the remaining breaks are largely due to code that only exists on `master`: the new v8 API!
> python: Backport dazl.damlast type fixes from v7.

- python/dazl/client/_party_client_impl.py
- python/dazl/client/api.py
- python/dazl/ledger/pkgloader_aio.py
- python/dazl/model/core.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/util/asyncio_util.py
- python/pytest.ini
- python/tests/unit/test_acs_find_active.py
- python/tests/unit/test_all_party.py
- python/tests/unit/test_all_types.py
- python/tests/unit/test_command_builder.py
- python/tests/unit/test_complicated_types.py
- python/tests/unit/test_config.py
- python/tests/unit/test_dynamic_parties.py
- python/tests/unit/test_event_order.py
- python/tests/unit/test_flask.py
- python/tests/unit/test_pb_serialize.py
- python/tests/unit/test_pending.py
- python/tests/unit/test_select.py
- python/tests/unit/test_server.py
- python/tests/unit/test_service_queue.py
- python/tests/unit/test_template_filtering.py
python: Tweaks, mostly to tests to ensure that deprecation warnings are handled appropriately in tests.
The vast majority of these warnings are in core parts of `dazl` where a user has no realistic way of suppressing warnings; until these bits of code are either themselves deprecated or changed to use symbols that will be supported going forward, they're suppressed.
> python: `DeprecationWarning` cleanup

- python/README.md
- python/dazl/client/_network_client_impl.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/api.py
- python/dazl/client/bots.py
- python/dazl/ledger/grpc/conn_aio.py
- python/dazl/ledger/pkgloader_aio.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/v1/grpc.py
- python/docs/migrating.rst
- python/tests/unit/test_acs_find_active.py
- python/tests/unit/test_all_party.py
- python/tests/unit/test_all_types.py
- python/tests/unit/test_autoload_explicit_packages.py
- python/tests/unit/test_complicated_types.py
- python/tests/unit/test_dotted_fields.py
- python/tests/unit/test_dynamic_parties.py
- python/tests/unit/test_map_support.py
- python/tests/unit/test_select.py
- python/tests/unit/test_server.py
- python/tests/unit/test_simple_client_api.py
- python/tests/unit/test_static_dump.py
- python/tests/unit/test_threadsafe_methods.py
- python/tests/unit/test_write_cancel.py
- python/tests/unit/test_write_cancel.py.orig
python: Some documentation updates, but the main course is actually adding support for returning results from exercise commands!
In writing documentation around changes on the write-side, I realized that it would be possible to expose `ExerciseResponse` results for the old API as well as the new one—it also helps make the two APIs more consistent with each other, along with better illustrating why some of these names have been changed.
> python: Documentation updates, Command submission changes

- python/docs/conf.py
- python/poetry.lock
- python/pyproject.toml
* Add the `sphinxcontrib_trio` plugin (https://sphinxcontrib-trio.readthedocs.io/en/latest/) as it does a much better rendering job on async methods, of which `dazl` has many.
* Drop the `sphinx.ext.viewcode` plugin, because the source links will be increasingly less helpful as the docs start to lean more heavily on rst files that live outside the code, and typing rules sometimes move to dedicated .pyi files.
* Fix a little warning around lexers and Sphinx—it prefers classes over instances.
> python: Add sphinxcontrib-trio to the docs.

- .circleci/config.yml
- .circleci/install-daml
- .circleci/install-jq
* Use the CircleCI base image instead of the older Java/Python image for Blackduck scans.
* Drop an unneeded copy of `jq` in the Blackduck run.
* Drop `--detect.python.python3=true` from Blackduck runs; it's currently configured to fail on warnings and now that Python 2 is unsupported, Synopsys has deprecated that flag.
* Add `set -x` to the various installers that run in CircleCI, because why not.
> meta: Minor fixes to the CircleCI setup.

- python/dazl/ledger/errors.py
- python/dazl/testing/__init__.py
- python/dazl/testing/connect.py
- python/dazl/testing/connect.pyi
- python/tests/unit/test_ledgerutil_acs.py
- python/tests/unit/test_ledgerutil_acs_close.py
- python/tests/unit/test_protocol_ledgerapi.py
In trying to fix another bug, I realized how verbose the code around writing tests was, and set out to try to reduce it.
The total amount of code is higher than I would have liked, but that's mostly because of Python 3.6 support; it could have been a lot less if I could have used `contextlib.asynccontextmanager` and `contextlib.AsyncExitStack`, but unfortunately those were introduced in Python 3.7.
> python: Add some test utilities.

- .gitattributes
Render Daml files as Haskell files, because it's better than no syntax highlighting at all.
> meta: Make Daml files render a little prettier in GitHub.

- scripts/publish.sh
meta: Fix the release script to include a leading 'v' in tag names.
Releases v7.5.0 through v7.5.3 have had their tags retroactively updated to fix the previously broken script that was in use for those four releases.
> meta: Fix the release script to include a leading 'v' in tag names.

- .circleci/config.yml
- .mypy.ini
I thought I had already merged this in but apparently not; make sure that `mypy` is run as part of the build.
`dazl` is finally now 100% happy with `mypy`, so this is to make sure it stays that way.
> python: Make sure that mypy is run as part of the build.

- Makefile
- poetry.lock
- pyproject.toml
- python/dazl/util/asyncio_util.py
* Update dependencies, particularly `mypy`:
* As of 0.900, mypy no longer includes typing definitions, so a few dev dependencies have also been added.
* Add pyjwt/cryptography as dev dependencies ahead of deeper SSL work.
> python: Update dependencies; add pyjwt/cryptography as dev dependencies

- python/dazl/protocols/v1/grpc.py
python: Give variables in `grpc_set_time` explicit names to avoid clashes in mypy.
Although the original code is legal Python, `mypy` gets confused that the `request` variables does double duty. For the moment, neither the previous nor the replacement code angers mypy,  That's only because there isn't yet a `.pyi` file for https://github.com/digital-asset/dazl-client/blob/8e7b5a887849e7e29abc17f6759cfe359e2123f8/python/dazl/_gen/com/daml/ledger/api/v1/testing/time_service_pb2.py, but the addition of one would trigger a problem here.
> python: Fix a potential typing bug with time service calls.

- python/dazl/ledger/grpc/codec_aio.py
- python/dazl/util/dar.py
python: A few more fixes to make `dazl`'s code compatible with a future auto-generated version of typing stub files.
> python: Some more typing fixes for Protobuf definitions.

- python/dazl/damlast/lookup.py
- python/dazl/damlast/pkgfile.py
- python/dazl/ledger/blocking/__init__.py
- python/dazl/ledger/blocking/__init__.pyi
- python/dazl/ledger/blocking/pkgloader.py
- python/tests/unit/test_pkg_loader_do_with_retry.py
This is a step on the way to a blocking "new-style" API to eventually replace the "old-style" blocking API.
There is a fair amount of duplication between the async and blocking implementations unfortunately, but Python's `asyncio` API and blocking calls are just ever so different that they require slightly different treatment. In addition the blocking API needs locks in ways that the the `asyncio` API does not, and trying to force code re-use where it's just not really possible just isn't worth it (I think).
> python: Add a blocking PackageLoader implementation.

- python/dazl/ledger/grpc/channel.py
- python/dazl/ledger/grpc/codec_aio.py
- python/dazl/ledger/grpc/conn_aio.py
- python/dazl/protocols/_base.py
- python/dazl/protocols/v1/grpc.py
- python/dazl/protocols/v1/pb_parse_event.py
- python/dazl/protocols/v1/pb_parse_metadata.py
- python/dazl/protocols/v1/pb_ser_command.py
- python/dazl/values/protobuf.py
- python/tests/unit/test_pb_serialize.py
- python/tests/unit/test_values_protobuf.py
Before #275, there wasn't a great way to avoid boilerplate and lengthy import sections for Protobuf-generated code. But now there is!
Wherever Protobuf types are used, do `from dazl._gen.com.daml.ledger.api import v1 as lapipb`  (Ledger API ProtoBuf).
> python: Simplify some imports.

- python/dazl/client/config.py
- python/dazl/model/__init__.py
- python/dazl/pretty/render_python.py
Fixed some leaky deprecation warnings that would happen even when deprecated types weren't explicitly imported.
> python: Fixed some leaky deprecation warnings

- docs/dazl.rst
- docs/dazl.testing.rst
- docs/testing.rst
- python/dazl/testing/__init__.py
- python/dazl/testing/_sandbox.py
- python/tests/conftest.py
- python/tests/unittest_example/unittest_example.py
python: Move some of the testing code for dazl into dazl itself so that it can be used by clients as well.
> python: Move some of the testing code for dazl into dazl itself

- poetry.lock
- pyproject.toml
python: Upgrade dependencies.
This also adds `async_exit_stack` as a shim for `contextlib.AsyncExitStack`, which was added to Python 3.7.
> python: Upgrade dependencies.

- docs/dazl.ledger.rst
docs: There is a problem with the docs under `dazl.ledger` (see https://discuss.daml.com/t/cannot-run-dazl-introductury-example/3503/2); this fixes that problem.
A longer term fix would be more in the style of #293 (moving the sample code to a file under unit tests), but I don't want to leave incorrect information out there.
> docs: Fix a problem with the docs under dazl.ledger.

- python/dazl/ledger/__init__.pyi
python: Add some typing rules left out of #300 by mistake.
> python: Add some typing rules left out of #300 by mistake.

- README.md
meta: Fix a link broken by the recent `master` -> `main` rename.
> meta: Fix a broken link.

- python/dazl/__init__.py
- python/dazl/ledger/__init__.py
- python/dazl/ledger/blocking/_aiowrapper.py
- python/tests/unit/test_ledger_blocking.py
python: Add support for a blocking API.
Even though the actual API is blocking, it still uses the underlying `aio`-flavored grpc library because it is vastly more performant than the blocking implementation on Python.
> python: Add support for a blocking API.

- Makefile
- pyproject.toml
- python/_dazl_pb/__init__.py
- python/_dazl_pb/protoc/__init__.py
- python/_dazl_pb/protoc/__main__.py
python: Add some internal utilities to try to tame the Protobuf/gRPC -> Python code generation process, specifically:
* Introduce a `_dazl_pb.protoc` module that wraps `grpc_tools.protoc`, but also adds the `site-packages` directory of the local Python installation. This makes almost built-ins like `google/rpc/status.proto` easier to find without any configuration.
* Introduce `_dazl_pb.protoc.protoc_plugin` for easily defining new `protoc` plugins in Python. It is not currently used in this PR, but the intended use of this and other utilities in this file will look like this:
```py
@protoc_plugin
def main(request: CodeGeneratorRequest) -> CodeGeneratorResponse:
python_response = run_plugin('python', request)
for f in python_response.file:
f.proto_file = COPYRIGHT_NOTICE + f.proto_file …
```
> python: Add some internal utilities for Protobuf/gRPC -> Python

- poetry.lock
- pyproject.toml
- python/dazl/ledger/config/access.py
- python/dazl/ledger/grpc/channel.py
- python/dazl/prim/datetime.py
- python/dazl/testing/_cert.py
- python/dazl/testing/_sandbox.py
- python/dazl/testing/connect.pyi
- python/tests/unit/test_ledger_tls.py
python: Introduce testing utilities for authorization and TLS.
* Bump up OpenSSL and cryptography dependencies—they were fairly ancient.
* Add a test that ensures that TLS support works.
* Minor changes to token handling to avoid sending locally-manufactured tokens.
> python: Introduce testing utilities for authorization and TLS.

- .circleci/config.yml
- _fixtures/scripts/generate.py
- _fixtures/src/all-kinds-of/AllKindsOf.daml
- _fixtures/src/complicated/Complicated.daml
- _fixtures/src/kitchen-sink/KitchenSink/Customer.daml
- _fixtures/src/kitchen-sink/KitchenSink/Supplier.daml
- _fixtures/src/kitchen-sink/KitchenSink/Warehouse.daml
- _fixtures/src/pending/Pending.daml
- _fixtures/src/post-office/Main.daml
- _fixtures/src/same-name-a/SameName.daml
- _fixtures/src/same-name-b/SameName.daml
- _fixtures/src/simple/Simple.daml
- _fixtures/src/test-server/TestServer.daml
- _fixtures/src/test-server/TestServerTest.daml
- _fixtures/src/test-server/daml.yaml
- python/tests/conftest.py
- python/tests/unit/test_pkg_loader_do_with_retry.py
- python/tests/unit/test_protocol_ledgerapi.py
- scripts/make/dars
meta: Correct a configuration error that prevented Daml 2.0 tests from actually running.
Also addressed:
* rewrote the Daml models to use Daml 2.0 syntax
In #329, I accidentally used `env` instead of `environment` in the CircleCI config file, which meant the dual-SDK-version tests weren't running as expected.
After fixing the initial error, I played around with a few different ways of triggering the tests (including tests that are, by design, supposed to only work with one or the other version). I stumbled across parameterized fixtures, which also solves nicely for being able to run the tests locally, so I switched to that instead.
> meta: Correct a configuration error that prevented Daml 2.0 tests from actually running.

- Makefile
- README.md
GNU Make "grouped targets" are a better way of specifying when build steps produce multiple artifacts, so start to move to that instead of trying to implement complicated logic in the Makefile to simulate that.
> meta: Simplify the makefile somewhat.

- pyproject.toml
- python/_dazl_pb/plugin_go/__init__.py
- python/_dazl_pb/plugin_go/_header.py
- python/_dazl_pb/plugin_go/plugin.py
- python/_dazl_pb/plugin_go/plugin_grpc.py
- python/_dazl_pb/plugin_go/plugin_pb.py
python: Generate gRPC/Protobuf stub files for Go.
This PR is merely about repackaging the Go gRPC/Protobuf generators in the same mechanics introduced in #315 for Python codegen.
> python: Generate gRPC/Protobuf stub files for Go.

- .circleci/config.yml
rapid scan on prs should lead to less false matches on prs, and is more scalable
> run rapid scan on prs, full scan only on master

- README.md
- docs/migrating.rst
- docs/testing.rst
Changed in the readme, and docs pages.
> Changing DAZLs name to 'The Daml Python bindings' in the repo

- python/dazl/client/api.py
- python/dazl/ledger/__init__.py
- python/dazl/ledger/errors.py
- python/dazl/ledger/grpc/codec_aio.py
- python/dazl/ledger/grpc/conn_aio.py
- python/dazl/values/canonical.py
python: As part of renaming `dazl` to "Python client binding libraries", remove references to `dazl` that are not linked to names of symbols in code.
> python: Drop explicit references to dazl in docs where it's not absolutely essential.

- python/dazl/util/tools.py
python: Remove dazl.util.tools.get_matches; it's been deprecated for a while and not used internally in dazl any more.
> python: Remove dazl.util.tools.get_matches.

- .circleci/install-daml
- python/tests/conftest.py
- python/tests/unit/test_ledger_metrics.py
python: Add tests that target the metering endpoints in Daml 2.3.
This is ahead of getting them to work with Daml 2.4, which changed the way that these services worked.
> python: Add tests for metering in Daml 2.3.

- python/_dazl_pb/syntax/python/symbols.py
- python/dazl/client/_party_client_impl.py
- python/dazl/client/state.py
- python/dazl/damlast/_builtins_meta.py
- python/dazl/damlast/builtins.py
- python/dazl/damlast/daml_lf_1.py
- python/dazl/damlast/eval_scope.py
- python/dazl/damlast/pkgfile.py
- python/dazl/ledger/__init__.pyi
- python/dazl/ledger/grpc/conn_aio.py
- python/dazl/model/types.py
- python/dazl/model/types_store.py
- python/dazl/pretty/table/model.py
- python/dazl/protocols/_base.py
- python/dazl/testing/connect.pyi
- python/dazl/util/asyncio_util.py
- python/dazl/util/dar_repo.py
python: Fix a handful of errors and warnings that are triggered by the latest version of mypy.
The version of mypy on the `v7` branch is behind `main`, so these violations wouldn't have necessarily failed the `v7` build, but they are currently preventing a merge to `main`.
> python: Fix various mypy violations.

- Makefile
- python/_dazl_pb/plugin_go/plugin_grpc.py
- python/_dazl_pb/plugin_go/plugin_pb.py
- python/_dazl_pb/protoc/__init__.py
- python/_dazl_pb/util/__init__.py
go: Cut out the code in the `Makefile` dedicated to generating Go protobuf/gRPC bindings, and move all the logic into the specialized plugin. Prior to this PR, there was weird logic in the plugin, and weird logic in the `Makefile`. This changes things so that only place has weird logic—the plugin.
> go: Simplify the process around building Go bindings.

- python/dazl/ledger/blocking/__init__.pyi
- python/tests/typing/test_connection.py
Introduce some tests that assert that `dazl.ledger.aio.Connection` and `dazl.ledger.blocking.Connection` and related types have (almost) matching signatures.
Turns out there's one function that is actually wrong! So I've ignored that for now, and will address in a subsequent PR.
> python: Add some type tests to ensure that Connection and QueryStream have mostly aligned type signatures.

- python/dazl/ledger/__init__.pyi
- python/dazl/ledger/config/__init__.py
- python/dazl/ledger/config/access.py
- python/dazl/ledger/config/log.py
- python/dazl/ledger/config/ssl.py
- python/dazl/ledger/config/url.py
Now that `Unpack` exists (https://peps.python.org/pep-0692/), it's possible to reduce some of the boilerplate around the type signatures of `connect`. 
So fix that, which also fixes a subtle error in the current set of typing rules: `retry_timeout` was never added to `connect` even though it's supported just fine.
> python: Properly type connect arguments.

- Makefile
- python/dazl/client/bots.py
- python/dazl/client/commands.py
- python/dazl/ledger/api_types.py
- python/dazl/ledger/grpc/conn_aio.py
- python/tests/conftest.py
- python/tests/unit/test_command.py
- python/tests/unit/test_command_builder.py
- python/tests/unit/test_command_py3_10.py
This is a bit of an experiment on the ergonomics of defining:
```python
Command = CreateCommand | ExerciseCommand | CreateAndExerciseCommand | ExerciseByKeyCommand
```
instead of the more traditional:
```python
class Command: ...
class CreateCommand(Command): ...
class ExerciseCommand(Command): ...
class CreateAndExerciseCommand(Command): ...
class ExerciseByKeyCommand(Command): ...
```
The advantage of using union types is mypy and other Python typecheckers can do a much better job of exhaustiveness checks. The disadvantage is that under Python 3.8 and Python 3.9, using union types breaks `isinstance` checks. This PR hacks around it by using defining alternate implementations for those two versions of Python, but keeping the typing definition union-based. (Side note: unfortunately Python …
> python: Redefine Command as a sealed type.

- python/dazl/testing/_sandbox.py
- python/dazl/util/proc_util.py
Numerous improvements to dazl to make them a little less fragile:
* Have the sandbox testing fixture hit the participant admin endpoint and actively check for `active` status before allowing tests to start. This should put an end to the `NO_DOMAIN_FOR_SUBMISSION` errors once and for all.
* Recent versions of Java seem to be more strict about TLS treatment, so make the participant start up with an explicit address of `localhost`, so that the SNI in our TLS test matches how we connect to it.
> python: Make the testing sandbox more resilient on startup.

- python/dazl/ledger/_retry.py
Many tests seem to be failing because of `NO_DOMAIN_FOR_SUBMISSION`; explicitly mark this kind of exception as a retryable.
> python: Automatically retry NO_DOMAIN_FOR_SUBMISSION.

- README.md
- docs/index.rst
Essentially, #531, but not as a fork of the repo.
> docs: Add a disclaimer that dazl does not work with 3.x.
