python/dazl/damlsdk/artifacts.yaml
python/dazl/pretty/scenario_serializer.py
python/dazl/protocols/v0/json_ser_command.py
python/tests/unit/dars.py

* Upgrade references of the SDK to 0.13.19.
* Fix some import errors.

python: Upgrade references of the SDK to 0.13.19

---

python/dazl/client/_party_client_impl.py

This one has been driving me nuts lately…quick add to give a bit more insight on app startup.

python: Minor logging improvements on app startup.

---

go/v7/go.mod
go/v7/go.sum
go/v7/pkg/client/ping.go
go/v7/pkg/testing/damlsdk.go
go/v7/pkg/testing/damlsdk_test.go
go/v7/pkg/testing/doc.go
go/v7/pkg/testing/sandbox.go
go/v7/pkg/testing/sandbox_test.go

go: Add functions for querying the local DAML SDK installation and for starting up a Sandbox.

go: Add utilities for running test Sandboxes.

---

python/dazl/protocols/v1/pb_parse_event.py

There are way too many errors and warnings in this file to make sense of this file in the IDE; this fixes all imports to that they actually work.

python: mypy fixes to pb_parse_event.

---

python/dazl/protocols/v1/grpc.py

Rewrite the `events` method to be a little less confusing.
Under certain configurations, this method takes the combination of the transaction tree stream and the transaction event stream and enriches the resultant stream with the contents of both. Both the previous version and the new version of the code run the two network calls in parallel, but the new version of this code does so in a way that avoids needing to create lower-level Futures explicitly.

python: Simplify the GRPCv1LedgerClient.events implementation slightly.

---

python/poetry.lock
python/pyproject.toml

python: Add black for autoformatting. Not running it on the whole codebase yet, but we'll start to use it for new and/or modified files.

python: Add black for autoformatting.

---

python/poetry.lock

python: Upgrade development-time dependency versions of components.

python: Update poetry dependencies.

---

python/dazl/__init__.py
python/dazl/cli/tail.py
python/dazl/client/_conn_settings.py
python/dazl/client/_events.py
python/dazl/client/_party_client_impl.py
python/dazl/client/_writer_verify.py
python/dazl/client/api.py
python/dazl/client/bots.py
python/dazl/client/ledger.py
python/dazl/model/__init__.py
python/dazl/protocols/_base.py
python/dazl/protocols/commands.py
python/dazl/protocols/v1/grpc.py
python/dazl/protocols/v1/pb_ser_command.py
python/tests/unit/blocking_setup.py
python/tests/unit/test_command_builder.py

python: Rename dazl.model.writing to dazl.protocols.commands.

python: Rename dazl.model.writing to dazl.protocols.commands.

---

python/dazl/ledgerutil/acs.py
python/tests/unit/test_ledgerutil_acs.py

This is not tested, but it should serve to illustrate the concept I'm advocating in your toplevel PR.

Detach ACS view read and write operations.

---

python/dazl/ledger/_offsets.py
python/dazl/ledger/grpc/conn_aio.py

Add support for resuming a transaction stream from an offset.…and remove another boolean flag!

python: Add support for resuming a transaction stream from an offset.

---

python/dazl/damlast/daml_lf_1.py

Replace `dazl/damlast/daml_lf_1.py` with the version from the v7 release branch to incorporate type fixes (see #207).

python: Backport v7: dazl/damlast/daml_lf_1.py

---

python/dazl/client/config.py

More backports in service of #207.

python: Backport dazl/client/config.py from the v7 release branch.

---

python/dazl/damlast/pb_parse.py

More backports in service of #207.

python: Backport dazl/damlast/pb_parse.py from the v7 release branch.

---

python/.gitignore
python/poetry.lock
python/pyproject.toml

Trying to reconcile the contents of the `master` and `release-7.3` branch by making more of the files identical to each other.

python: Backport some basic build files to the release 7.3 branch.

---

python/dazl/client/_network_client_impl.py
python/dazl/client/_party_client_impl.py
python/dazl/client/_reader_sync.py
python/dazl/client/_run_level.py
python/dazl/client/api.py
python/dazl/client/bots.py
python/dazl/client/state.py
python/dazl/model/writing.py
python/tests/unit/test_pb_serialize.py

Backport type fixes to `dazl.client` from the v7 branch to `master`.

python: Backport dazl.client type fixes from v7 to master.

---

python/dazl/client/_base_model.py
python/dazl/client/_conn_settings.py
python/dazl/client/bots.py
python/dazl/client/commands.py
python/dazl/client/errors.py
python/dazl/client/state.py
python/dazl/ledger/_offsets.py
python/dazl/ledger/config/exc.py
python/dazl/ledger/config/ssl.py
python/dazl/ledger/config/url.py
python/dazl/ledger/grpc/__init__.py
python/dazl/ledger/grpc/__init__.pyi
python/dazl/ledger/grpc/channel.py
python/dazl/ledger/grpc/codec_aio.py
python/dazl/ledger/grpc/conn_aio.py
python/dazl/ledger/pkgloader_aio.py
python/dazl/ledger/pkgloader_aio_compat.py
python/dazl/ledgerutil/acs.py
python/dazl/protocols/events.py
python/dazl/protocols/serializers.py
python/dazl/protocols/v1/grpc.py
python/dazl/protocols/v1/pb_ser_command.py
python/mypy.ini

This PR makes `mypy` 100% happy with `master`! It also fixes a few bugs in the dazl v8 API that were very easy to catch with a typechecker. :-D
This will probably be the last PR before the `release-7.3` is _finally_ merged into master; the first release candidate of v7.5.0 is basically this PR.

python: Type fixes to the dazl v8 dazl.ledger API.

---

python/dazl/damlast/__init__.py
python/dazl/damlast/lookup.py
python/dazl/ledger/api_types.py
python/dazl/ledger/config/__init__.py
python/dazl/prim/__init__.py
python/docs/migrating.rst

python: More little docs fixes.

python: Minor docs fixes.

---

Makefile
_fixtures/src/same-name-a/SameName.daml
_fixtures/src/same-name-a/daml.yaml
_fixtures/src/same-name-b/SameName.daml
_fixtures/src/same-name-b/daml.yaml
scripts/make/dars

python: Add test Daml that uses the same name (to test whether or not dazl can handle this case).

python: Add test Daml that uses the same name

---

Makefile
poetry.lock
pyproject.toml
python/tests/conftest.py
python/tests/unit/dars.py
python/tests/unit/test_all_types.py
python/tests/unit/test_pb_serialize.py
python/tests/unit/test_server.py

python: Run mypy over the tests as well as the main source code for dazl.

python: Run mypy over the tests as well as the main source code

---

Makefile

meta: Make the `make clean` target clean more things.

meta: A cleaner make clean.

---

pyproject.toml
python/tests/structure/test_structure.py
python/tests/unit/__init__.py
python/tests/unit/blocking_setup.py
python/tests/unit/test_autoload_explicit_packages.py
python/tests/unit/test_daml_lf_1.py
python/tests/unit/test_damlast_parse_type_con_name.py
python/tests/unit/test_ledgerutil_acs.py
python/tests/unit/test_ledgerutil_acs_close.py
python/tests/unit/test_prim_decimal_to_str.py
python/tests/unit/test_query.py
python/tests/unit/test_startup_errors.py
python/tests/unit/test_template_filtering.py

python: Added a little test to make sure that all files have copyright notices.

python: Added a little test to make sure that all files have copyright notices.

---

samples/ping-pong/poetry.lock

samples: Update the lock file to pick up newer versions of dependencies.

samples: Update lockfile dependencies.

---

docs/dazl.ledger.rst
python/dazl/ledger/__init__.py
python/dazl/ledger/__init__.pyi
python/dazl/ledger/aio/__init__.pyi
python/dazl/ledger/api_types.py
python/dazl/ledger/blocking/__init__.pyi
python/dazl/ledger/grpc/conn_aio.py
python/dazl/prim/__init__.py
python/dazl/prim/party.py

python: Add support for `read_as` and `act_as` overrides when sending commands or performing queries.

python: Add support for read-as and act-as overrides.

---

.circleci/config.yml

User circleci environment variables for project name and branch to determinally dynamically for scan

dynamically get branch name for blackduck scans

---

oldidea/.gitignore
oldidea/da-dazl.iml
oldidea/inspectionProfiles/Project_Default.xml
oldidea/inspectionProfiles/profiles_settings.xml
oldidea/markdown.xml
oldidea/misc.xml
oldidea/modules.xml
oldidea/vcs.xml
python/tests/unit/test_ledger_stream.py

python: Add a test case that ensures that streams behave as expected.

python: Add a test case that ensures that streams behave as expected.

---

poetry.lock
python/dazl/ledger/api_types.py

python: Update mypy dependency to 0.940.

python: Update mypy dependency to 0.940.

---

poetry.lock

Upgrading the development-time dependencies.

python: Bump versions of dependencies.

---

poetry.lock
python/dazl/ledger/aio/pkgloader.py

python: Bump development-time dependencies.

python: Bump development-time dependencies.

---

docs/dazl.model.rst
docs/dazl.rst
samples/ping-pong/pingpong/bots.py

docs: Remove references to `dazl.model`, as that module has been removed in v8.

docs: Remove references to dazl.model, as that module has been removed.

---

README.md
docs/migrating.rst
docs/testing.rst
python/dazl/client/api.py
python/dazl/ledger/__init__.py
python/dazl/ledger/errors.py
python/dazl/ledger/grpc/codec_aio.py
python/dazl/ledger/grpc/conn_aio.py
python/dazl/values/canonical.py

Cherry-picks of these PRs:
* #371
* #372

meta: Backport recent docs changes from the main branch to v7.

---

docs/migrating.rst

Fix an incomplete sentence in the documentation.

python: Fix an incomplete sentence.

---

.mypy.ini
poetry.lock

python: Update dependencies (v7 branch).

---

.circleci/config.yml

python: Bump up Python versions in CircleCI.

python: Update versions of Python used in CircleCI.

---

poetry.lock

python: Bump versions.

---

pyproject.toml

python: Add [build-system] to pyproject.toml.

---

python/tests/unit/test_ledger_create_and_exercise.py

A random test I had sitting on a branch on my computer… no reason not to add it!

python: Add a test case for CreateAndExerciseCommand.

---

python/dazl/client/commands.py
python/dazl/ledger/__init__.pyi
python/dazl/ledger/aio/__init__.pyi
python/dazl/ledger/api_types.py
python/dazl/ledger/blocking/__init__.pyi
python/dazl/ledger/config/__init__.py
python/dazl/ledger/config/access.py
python/dazl/ledger/grpc/__init__.pyi
python/dazl/ledger/grpc/conn_aio.py
python/dazl/prim/__init__.py
python/dazl/prim/party.py
python/dazl/testing/connect.py
python/dazl/testing/connect.pyi

Introduce `Parties` and `Commands` to make some of the types a little cleaner and easier to read.

python: Introduce a convenience type for parties and commands.

---

Makefile
_fixtures/src/kitchen-sink-sdk29-lf-1-16/README.md
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink-interfaces/KitchenSink/Interfaces/HasLocation.daml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink-interfaces/daml.yaml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink/KitchenSink/Customer.daml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink/KitchenSink/Retailer.daml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink/KitchenSink/SKU.daml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink/KitchenSink/Supplier.daml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink/KitchenSink/Warehouse.daml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/kitchen-sink/daml.yaml
_fixtures/src/kitchen-sink-sdk29-lf-1-16/multi-package.yaml
python/_dazl/download/__init__.py
python/dazl/testing/_sandbox.py
python/tests/conftest.py
python/tests/unit/config.py
python/tests/unit/dars.py
python/tests/unit/test_historical_dar_parsing.py
python/tests/unit/test_ledger_token.py

Add test cases for Daml 2.9.1 and Daml-LF 1.16 DARs.

python: Test against protocol v6 and add support for Daml-LF 1.16.
